#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <stdbool.h> 
#include "arm_math.h"
#include "arm_nnfunctions.h"
#include "parameters.h"
#include "weights.h"

/*
Example of code generated by hand for an square input image,
using only convolutions and fully connected layers and 
8 bit quantization of CMSIS legacy
*/

q7_t conv1_out[CONV1_OUT_CH*CONV1_OUT_DIM*CONV1_OUT_DIM];
q7_t conv2_out[CONV2_OUT_CH*CONV2_OUT_DIM*CONV1_OUT_DIM];
q7_t fc1_out[FC1_OUT];
q7_t y_out[FC1_OUT];

q7_t conv1_w[CONV1_WT_SHAPE] = CONV1_WT;
q7_t conv1_b[CONV1_BIAS_SHAPE] = CONV1_BIAS;
q7_t conv2_w[CONV2_WT_SHAPE] =  CONV2_WT;
q7_t conv2_b[CONV2_BIAS_SHAPE] = CONV2_BIAS;
q7_t fc1_w[FC1_WT_SHAPE] = FC1_WT;
q7_t fc1_b[FC1_BIAS_SHAPE] = FC1_BIAS;

q7_t conv_buffer[MAX_CONV_BUFFER_SIZE];
q7_t fc_buffer[MAX_FC_BUFFER];
// q7_t conv_buffer[3000];
// q7_t fc_buffer[10000];

q7_t* load(const char* file)
{
	size_t sz;
	q7_t* in;
	FILE* fp = fopen(file,"rb");
	assert(fp);
	fseek(fp, 0, SEEK_END);
	sz = ftell(fp);
	fseek(fp, 0, SEEK_SET);
	in = malloc(sz);
	fread(in, 1, sz, fp);
	fclose(fp);
	return in;
}

void save(const char* file, q7_t* out, size_t sz)
{
	FILE* fp = fopen(file,"wb");
	fwrite(out, 1, sz, fp);
	fclose(fp);
}

uint32_t network(q7_t* input)
{
	arm_convolve_HWC_q7_basic(input, CONV1_IM_DIM, CONV1_IM_CH, conv1_w, CONV1_OUT_CH, CONV1_KER_DIM, CONV1_PADDING,
						  CONV1_STRIDE, conv1_b, CONV1_BIAS_LSHIFT, CONV1_OUT_RSHIFT, conv1_out, CONV1_OUT_DIM,
						  (q15_t *) conv_buffer, fc_buffer);
	save("logs/conv1_out.raw", conv1_out, sizeof(conv1_out));

    // first relu
    arm_relu_q7(conv1_out, CONV1_OUT_DIM * CONV1_OUT_DIM * CONV1_OUT_CH);

    // second conv
    arm_convolve_HWC_q7_basic(conv1_out, CONV2_IM_DIM, CONV2_IM_CH, conv2_w, CONV2_OUT_CH, CONV2_KER_DIM,
						  CONV2_PADDING, CONV2_STRIDE, conv2_b, CONV2_BIAS_LSHIFT, CONV2_OUT_RSHIFT, conv2_out,
						  CONV2_OUT_DIM, (q15_t *) conv_buffer, NULL);
	save("logs/conv2_out.raw", conv2_out, sizeof(conv2_out));

    // second relu
	arm_relu_q7(conv2_out, CONV2_OUT_DIM * CONV2_OUT_DIM * CONV2_OUT_CH);

    // first fc
	arm_fully_connected_q7_opt(conv2_out, fc1_w, FC1_DIM, FC1_OUT, FC1_BIAS_LSHIFT, FC1_OUT_RSHIFT, fc1_b,
						  fc1_out, (q15_t *) fc_buffer);
	save("logs/fc1_out.raw", fc1_out, sizeof(fc1_out));

    // softmax
    arm_softmax_q7(fc1_out, FC1_OUT, y_out);
	save("logs/y_out.raw", y_out, sizeof(y_out));

	uint32_t index[1];
	q7_t result[1];
	uint32_t blockSize = sizeof(y_out);

	arm_max_q7(y_out, blockSize, result, index);
	//printf("Classified class %i\n", index[0]);

	return index[0];
}

int main(int argc, char** argv)
{
	q7_t *input;
    input = load("logs/input.raw");
    uint32_t index;
    index = network(input);
	return 0;
}