#define CONV1_BIAS_LSHIFT 5
#define CONV1_OUT_RSHIFT 8
#define CONV1_Q 8
#define CONV1_BIAS_Q 8
#define CONV1_INPUT_Q 5
#define CONV1_OUT_Q 5
#define CONV2_BIAS_LSHIFT 4
#define CONV2_OUT_RSHIFT 9
#define CONV2_Q 8
#define CONV2_BIAS_Q 9
#define CONV2_INPUT_Q 5
#define CONV2_OUT_Q 4
#define CONV3_BIAS_LSHIFT 4
#define CONV3_OUT_RSHIFT 8
#define CONV3_Q 8
#define CONV3_BIAS_Q 9
#define CONV3_INPUT_Q 5
#define CONV3_OUT_Q 5
#define IP1_BIAS_LSHIFT 6
#define IP1_OUT_RSHIFT 10
#define IP1_Q 8
#define IP1_BIAS_Q 8
#define IP1_INPUT_Q 6
#define IP1_OUT_Q 4
#define IP2_BIAS_LSHIFT 4
#define IP2_OUT_RSHIFT 6
#define IP2_Q 8
#define IP2_BIAS_Q 8
#define IP2_INPUT_Q 4
#define IP2_OUT_Q 6
#define CONV1_IM_CH 3
#define CONV1_OUT_CH 16
#define CONV1_KER_DIM 3
#define CONV1_PADDING 0
#define CONV1_STRIDE 1
#define CONV1_IM_DIM 32
#define CONV1_OUT_DIM 30
#define CONV2_IM_CH 16
#define CONV2_OUT_CH 8
#define CONV2_KER_DIM 3
#define CONV2_PADDING 0
#define CONV2_STRIDE 1
#define CONV2_IM_DIM 30
#define CONV2_OUT_DIM 28
#define CONV3_IM_CH 8
#define CONV3_OUT_CH 4
#define CONV3_KER_DIM 3
#define CONV3_PADDING 0
#define CONV3_STRIDE 1
#define CONV3_IM_DIM 28
#define CONV3_OUT_DIM 26
#define IP1_OUT 32
#define IP1_DIM 2704
#define IP2_OUT 10
#define IP2_DIM 32
