#define CONV1_BIAS_LSHIFT 4
#define CONV1_OUT_RSHIFT 9
#define CONV1_Q 7
#define CONV1_BIAS_Q 8
#define CONV1_INPUT_Q 5
#define CONV1_OUT_Q 3
#define CONV2_BIAS_LSHIFT 1
#define CONV2_OUT_RSHIFT 8
#define CONV2_Q 7
#define CONV2_BIAS_Q 9
#define CONV2_INPUT_Q 3
#define CONV2_OUT_Q 2
#define FC1_BIAS_LSHIFT 1
#define FC1_OUT_RSHIFT 9
#define FC1_Q 8
#define FC1_BIAS_Q 9
#define FC1_INPUT_Q 2
#define FC1_OUT_Q 1
#define FC2_BIAS_LSHIFT 0
#define FC2_OUT_RSHIFT 7
#define FC2_Q 8
#define FC2_BIAS_Q 9
#define FC2_INPUT_Q 1
#define FC2_OUT_Q 2
#define CONV1_IM_CH 1
#define CONV1_OUT_CH 8
#define CONV1_KER_DIM 5
#define CONV1_PADDING 0
#define CONV1_STRIDE 1
#define CONV1_IM_DIM 28
#define CONV1_OUT_DIM 24
#define MAX_CONV_BUFFER_SIZE 144
#define POOL1_OUT_CH 8
#define POOL1_IM_CH 8
#define POOL1_KER_DIM 2
#define POOL1_PADDING 0
#define POOL1_STRIDE 2
#define POOL1_IM_DIM 24
#define POOL1_OUT_DIM 12
#define CONV2_IM_CH 8
#define CONV2_OUT_CH 4
#define CONV2_KER_DIM 3
#define CONV2_PADDING 0
#define CONV2_STRIDE 1
#define CONV2_IM_DIM 12
#define CONV2_OUT_DIM 10
#define POOL2_OUT_CH 4
#define POOL2_IM_CH 4
#define POOL2_KER_DIM 2
#define POOL2_PADDING 0
#define POOL2_STRIDE 2
#define POOL2_IM_DIM 10
#define POOL2_OUT_DIM 5
#define FC1_OUT 32
#define FC1_DIM 100
#define MAX_FC_BUFFER 100
#define FC2_OUT 10
#define FC2_DIM 32
